[package]
name = "stm32ral-example"
version = "0.1.0"
authors = ["Adam Greig <adam@adamgreig.com>"]

[dependencies]
cortex-m = { version = "0.5.4", features = ["inline-asm"] }
cortex-m-rt = "0.5.2"
panic-abort = "0.2.0"

[dependencies.stm32ral]
path = "/home/adam/Projects/stm32ral"
features = ["stm32f405", "rt"]
default-features = false

[profile.dev]
opt-level = 1

[profile.release]
debug = true
lto = true
codegen-units = 1
incremental = false
